spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academyChallenge
    username: postgres
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
